# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            PixelChips.info
tagline:          'Silicon Pixel Sesnosrs, Chip Design, Physics'
url:              http://www.pixelchips.info
shorturl:         pixelchips.info

author:
  name:           'Tomasz Hemperek'
  url:            https://twitter.com/themperek

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/themperek/themperek.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
